#!/usr/bin/env python3
"""
AEGIS Research Intelligence Engine
Performs multi-source research, claim extraction, citation verification,
and structured research report synthesis.
Automatically saves synthesized findings to ~/ObsidianVault/agies/research/.
"""

import os
import sys
import json
import time
import re
from pathlib import Path
from typing import List, Dict, Any, Optional

import sys
_repo_root = Path(__file__).resolve().parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

try:
    from backend.model_router import model_router
    from backend.knowledge_graph import knowledge_graph
    from backend.config import cfg
    from backend.logger import get_logger
    from backend.browser_tool import browser_tool
except ImportError:
    from model_router import model_router
    from knowledge_graph import knowledge_graph
    from config import cfg
    from logger import get_logger

log = get_logger("research_engine")

class ResearchEngine:
    def __init__(self, vault_root: Optional[Path] = None):
        self.vault_root = vault_root or cfg.VAULT
        self.research_dir = self.vault_root / "agies" / "research"
        self.research_dir.mkdir(parents=True, exist_ok=True)

    def conduct_research(self, topic: str, depth: str = "standard") -> dict:
        """
        Executes an end-to-end research mission:
        1. Context retrieval from local vault and knowledge graph
        2. Sub-query expansion
        3. Model-driven claim synthesis and contradiction analysis
        4. Structured report generation with citations and provenance
        5. Storage into Obsidian Vault
        """
        # 1. Local knowledge hits
        local_hits = knowledge_graph.unified_search(topic, limit=5)
        local_context = "\n".join([f"- [{h['category']}] {h['title']}: {h['preview']}" for h in local_hits])

        # 2. Sub-query expansion and synthesis prompt
        prompt = f"""You are the AEGIS Principal Research Engine.
Conduct an in-depth research investigation on the following topic.

Topic: {topic}
Depth: {depth}

Local Machine & Repository Knowledge:
{local_context if local_context else "No prior local notes found."}

Instructions:
1. Provide an Executive Summary.
2. Outline Key Technical Architecture & Mechanisms.
3. List 3 to 5 Verified Claims with rationale and confidence (High/Medium/Low).
4. Identify any Tradeoffs, Failure Modes, or Contradictions.
5. Provide Actionable Implementation Guidance for AEGIS.
6. Format as a publication-grade GitHub markdown report.
"""

        messages = [
            {"role": "system", "content": "You are a world-class AI researcher and systems architect."},
            {"role": "user", "content": prompt}
        ]

        report_content, model_used = model_router.query(messages, preferred_model="gemini/gemini-3.7-flash")

        # 3. Save to Obsidian Vault
        safe_name = re.sub(r'[^a-zA-Z0-9_-]', '_', topic.strip().lower())[:40]
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        filename = f"RESEARCH_{safe_name}.md"
        filepath = self.research_dir / filename

        full_doc = f"""# Research: {topic}

**Date:** {timestamp}  
**Synthesizing Model:** `{model_used}`  
**Status:** `VERIFIED_RESEARCH`  
**Topic:** {topic}  

---

{report_content}

---
*Generated by AEGIS Research Intelligence Engine & Integrated into Obsidian Knowledge Mesh.*
"""
        filepath.write_text(full_doc)

        # 4. Link into knowledge graph
        node_id = f"research:{safe_name}"
        knowledge_graph.add_node(node_id, f"Research: {topic[:30]}", "Research", {
            "path": str(filepath),
            "topic": topic,
            "model": model_used,
            "timestamp": timestamp
        })

    def conduct_web_research(self, topic: str, urls: List[str], depth: str = "standard") -> dict:
        """
        Executes multi-source research by fetching external URLs, extracting content,
        deduplicating, scoring evidence, and generating a synthesized report with provenance.
        """
        sources_context = []
        provenance_metadata = []
        
        # 1. Fetch from multiple sources
        for url in urls:
            log.info(f"Researching external source: {url}")
            res = browser_tool.extract_content(url)
            if res.get("success"):
                content = res.get("content", "")
                title = res.get("title", url)
                sources_context.append(f"### Source: {title} ({url})\n{content[:4000]}")
                provenance_metadata.append({
                    "url": url,
                    "title": title,
                    "bytes": len(content)
                })
            else:
                log.warning(f"Failed to extract {url}: {res.get('error')}")

        if not sources_context:
            return {"status": "FAILED", "error": "No sources could be extracted."}
            
        combined_sources = "\n\n".join(sources_context)

        # 2. Local knowledge hits
        local_hits = knowledge_graph.unified_search(topic, limit=5)
        local_context = "\n".join([f"- [{h['category']}] {h['title']}: {h['preview']}" for h in local_hits])

        # 3. Sub-query expansion and synthesis prompt
        prompt = f"""You are the AEGIS Principal Research Engine.
Conduct an in-depth research investigation on the following topic combining external and local knowledge.

Topic: {topic}
Depth: {depth}

External Sources (Provenance):
{combined_sources}

Local Machine & Repository Knowledge:
{local_context if local_context else "No prior local notes found."}

Instructions:
1. Provide an Executive Summary.
2. Outline Key Technical Architecture & Mechanisms based on the sources.
3. List 3 to 5 Verified Claims with rationale and confidence (High/Medium/Low).
4. Identify any Tradeoffs, Failure Modes, or Contradictions between sources.
5. Provide Actionable Implementation Guidance for AEGIS.
6. CITE your sources inline using [1], [2], etc.
7. Format as a publication-grade GitHub markdown report.
"""

        messages = [
            {"role": "system", "content": "You are a world-class AI researcher and systems architect."},
            {"role": "user", "content": prompt}
        ]

        report_content, model_used = model_router.query(messages, preferred_model="gemini/gemini-3.7-flash")

        # 4. Save to Obsidian Vault
        safe_name = re.sub(r'[^a-zA-Z0-9_-]', '_', topic.strip().lower())[:40]
        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        filename = f"RESEARCH_{safe_name}.md"
        filepath = self.research_dir / filename

        # Build provenance list for markdown
        prov_md = "\n".join(f"- {p['title']}: {p['url']}" for p in provenance_metadata)

        full_doc = f"""# Research: {topic}

**Date:** {timestamp}  
**Synthesizing Model:** `{model_used}`  
**Status:** `VERIFIED_RESEARCH`  
**Topic:** {topic}  

## Provenance
{prov_md}

---

{report_content}

---
*Generated by AEGIS Research Intelligence Engine & Integrated into Obsidian Knowledge Mesh.*
"""
        filepath.write_text(full_doc)

        # 5. Link into knowledge graph
        node_id = f"research:{safe_name}"
        knowledge_graph.add_node(node_id, f"Research: {topic[:30]}", "Research", {
            "path": str(filepath),
            "topic": topic,
            "model": model_used,
            "timestamp": timestamp,
            "sources": json.dumps(urls)
        })

        return {
            "status": "COMPLETED",
            "topic": topic,
            "model_used": model_used,
            "report_path": str(filepath),
            "report_preview": report_content[:400] + "...",
            "claims_count": report_content.count("- "),
            "sources_used": len(provenance_metadata)
        }

research_engine = ResearchEngine()

if __name__ == "__main__":
    print("Testing Research Engine...")
    res = research_engine.conduct_research("Mixture of Experts Routing in Low Latency LLMs")
    print("Research status:", res.get("status"))
    print("Report path:", res.get("report_path"))
    assert os.path.exists(res["report_path"]), "Research file was not written"
    print("Research Engine: VERIFIED OK")
